# SoLab 爬虫配置文件
# 配置各种爬虫的预设参数

# 爬虫预设配置
crawlers:
  # Jupiter 相关预设
  jupiter:
    # 热门交易代币预设
    toptraded:
      # 低市值可疑交易量预设 - 5分钟
      lowCapSusVol_5m:
        timeFrame: "5m"
        mintAuthorityDisabled: true
        freezeAuthorityDisabled: true
        minLiquidity: 3000
        minVolume: 750
        maxMcap: 100000
        hasSocials: true
        minTokenAge: 1500 # 单位是分钟
        # 持有者分析筛选条件
        min_holders: 8  # 至少5个地址持有同一代币
        min_total_value: 10000  # 总价值超过10万美元
      
      # 趋势代币预设 - 24小时
      trending_24h:
        timeFrame: "24h"
        mintAuthorityDisabled: true
        freezeAuthorityDisabled: true
        minLiquidity: 3000
        minMcap: 100000
        maxMcap: 10000000
        hasSocials: true
        # 持有者分析筛选条件
        min_holders: 8  # 至少8个地址持有同一代币
        min_total_value: 500000  # 总价值超过50万美元
      
      # 低市值潜力代币预设 - 24小时
      lowCapGem_24h:
        timeFrame: "24h"
        mintAuthorityDisabled: true
        freezeAuthorityDisabled: true
        minLiquidity: 3000
        minVolume: 3000
        maxVolume: 100000
        minMcap: 30000
        maxMcap: 60000
        hasSocials: true
        minTokenAge: 600 # 单位是分钟
        # 持有者分析筛选条件
        min_holders: 8  # 至少7个地址持有同一代币
        min_total_value: 30000  # 总价值超过30万美元
      
      # 最低市值潜力代币预设 - 24小时
      lowestCapGem_24h:
        timeFrame: "24h"
        mintAuthorityDisabled: true
        freezeAuthorityDisabled: true
        minLiquidity: 3000
        minVolume: 750
        maxVolume: 100000
        minMcap: 9000
        maxMcap: 30000
        hasSocials: true
        minTokenAge: 2840 # 单位是分钟
        # 持有者分析筛选条件
        min_holders: 8  # 至少6个地址持有同一代币
        min_total_value: 10000  # 总价值超过20万美元
      
      # Gake 功能专用预设 - 1小时
      1H:
        timeFrame: "1h"
        mintAuthorityDisabled: true
        freezeAuthorityDisabled: true
        minVolume: 1000
        minMcap: 10000
        maxMcap: 30000
        hasSocials: true
        minTokenAge: 720 # 单位是分钟



# 爬虫性能配置
crawler_performance:
  # OKX 地址资产爬虫配置
  okx_address_balance:
    # 保守模式 - 最稳定，适合长期运行
    conservative:
      max_workers: 1
      base_delay: 1.0
      timeout: 5.0
      expected_speed: 1.2  # 地址/秒
      success_rate: 100.0
      description: "最稳定配置，适合长期批量处理"
    
    # 平衡模式 - 速度与稳定性兼顾
    balanced:
      max_workers: 3
      base_delay: 0.5
      timeout: 5.0
      expected_speed: 2.6  # 地址/秒
      success_rate: 100.0
      description: "推荐日常使用，速度稳定性兼顾"
    
    # 高速模式 - 追求最大速度
    high_speed:
      max_workers: 6
      base_delay: 0.2
      timeout: 5.0
      expected_speed: 3.4  # 地址/秒
      success_rate: 100.0
      description: "极限速度配置，适合急速处理"
    
    # 轻量模式 - 适合网络较差环境
    lightweight:
      max_workers: 2
      base_delay: 0.8
      timeout: 8.0
      expected_speed: 2.0  # 地址/秒
      success_rate: 100.0
      description: "适合网络不稳定环境"

  # OKX 代币交易历史爬虫配置
  okx_token_trading_history:
    high_speed:
      max_workers: 5
      base_delay: 0.1
      timeout: 8.0
      expected_speed: 4.0  # 请求/秒
      success_rate: 100.0
      description: "代币交易历史高速获取配置"

    balanced:
      max_workers: 3
      base_delay: 0.5
      timeout: 10.0
      expected_speed: 2.0  # 请求/秒
      success_rate: 100.0
      description: "代币交易历史平衡配置"

  # OKX 地址代币列表爬虫配置
  okx_address_token_list:
    high_speed:
      max_workers: 4
      base_delay: 0.2
      timeout: 5.0
      expected_speed: 3.5  # 地址/秒
      success_rate: 100.0
      description: "地址代币列表高速获取配置"

    balanced:
      max_workers: 3
      base_delay: 0.5
      timeout: 5.0
      expected_speed: 2.6  # 地址/秒
      success_rate: 100.0
      description: "地址代币列表平衡配置"

# Cabal代币配置
cabal_tokens:
  # 已知的操控代币合约地址列表
  addresses:
    - "So11111111111111111111111111111111111111112"  # SOL (WSOL)
    # 在此添加更多已知的cabal代币地址

  # 可疑地址判断标准
  suspicious_criteria:
    max_tx_count_7d: 30    # 7天最大交易次数阈值
    max_tx_count_30d: 50   # 30天最大交易次数阈值
    min_suspicious_addresses: 2  # 触发警报的最少可疑地址数

# Gake监控配置
gake_monitor:
  # 价格涨幅阈值 (百分比)
  price_increase_threshold: 3.0
  # 监控间隔 (秒)
  snapshot_interval: 20
  # 市值范围
  min_market_cap: 10000
  max_market_cap: 30000
  # 最小1小时成交量
  min_volume_1h: 1000
  # 最小代币年龄 (分钟)
  min_age_minutes: 720

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/solab.log"